name: Continuos Integration

on:
  pull_request_review:
    types:
      - submitted
    branches:
      - main

jobs:
  continuos_integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.1
      - name: run install, build and test
        run: |
          yarn
          yarn build
          yarn test
